import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1764086538424 implements MigrationInterface {
    name = 'InitSchema1764086538424'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "task_comments" ("id" SERIAL NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "taskId" integer, "userId" integer, CONSTRAINT "PK_83b99b0b03db29d4cafcb579b77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "url" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "taskId" integer, "uploadedById" integer, CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commits" ("id" SERIAL NOT NULL, "hash" character varying NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "repoId" integer, "authorId" integer, CONSTRAINT "PK_87adcaf9b8d0f42fee0481c0917" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "repos" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "githubUrl" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" integer, CONSTRAINT "PK_50f4cdbc4e114515f41760400ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pull_requests_status_enum" AS ENUM('open', 'closed', 'merged')`);
        await queryRunner.query(`CREATE TABLE "pull_requests" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "status" "public"."pull_requests_status_enum" NOT NULL DEFAULT 'open', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "repoId" integer, "createdById" integer, CONSTRAINT "PK_e8a8aa8710c3a9650a19a9c2e7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pr_task_links" ("id" SERIAL NOT NULL, "pullRequestId" integer, "taskId" integer, CONSTRAINT "PK_2a5e61688b0e041be6b18719295" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('todo', 'in_progress', 'done')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "status" "public"."tasks_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "sprintId" integer, "projectId" integer, "assigneeId" integer, "reporterId" integer, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "projectId" integer, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."test_runs_status_enum" AS ENUM('pass', 'fail', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "test_runs" ("id" SERIAL NOT NULL, "status" "public"."test_runs_status_enum" NOT NULL DEFAULT 'pass', "executedAt" TIMESTAMP NOT NULL DEFAULT now(), "testCaseId" integer, "executedById" integer, CONSTRAINT "PK_ec4eca50c7ddfbd0dcf89b46dc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "test_cases" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "projectId" integer, CONSTRAINT "PK_39eb2dc90c54d7a036b015f05c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."deployments_status_enum" AS ENUM('success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "deployments" ("id" SERIAL NOT NULL, "status" "public"."deployments_status_enum" NOT NULL, "deployedAt" TIMESTAMP NOT NULL DEFAULT now(), "environmentId" integer, "deployedById" integer, CONSTRAINT "PK_1e5627acb3c950deb83fe98fc48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "environments" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "projectId" integer, CONSTRAINT "PK_ec32d12469ec3c2f2f20c4f5e71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."builds_status_enum" AS ENUM('success', 'failed', 'running')`);
        await queryRunner.query(`CREATE TABLE "builds" ("id" SERIAL NOT NULL, "status" "public"."builds_status_enum" NOT NULL DEFAULT 'running', "startedAt" TIMESTAMP NOT NULL DEFAULT now(), "finishedAt" TIMESTAMP, "projectId" integer, "triggeredById" integer, CONSTRAINT "PK_c181c897db1d7b044faace6e86c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "teamId" integer, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teams_type_enum" AS ENUM('personal', 'team')`);
        await queryRunner.query(`CREATE TABLE "teams" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "type" "public"."teams_type_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "ownerUserId" integer, CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_team_roles_role_enum" AS ENUM('admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "user_team_roles" ("id" SERIAL NOT NULL, "role" "public"."user_team_roles_role_enum" NOT NULL, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "teamId" integer, CONSTRAINT "PK_9adc6cc0b81b7e7327fa54e02d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_platform_role_enum" AS ENUM('super_admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "name" character varying NOT NULL, "github_token" character varying, "platform_role" "public"."users_platform_role_enum" NOT NULL DEFAULT 'user', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "uploadedById" integer, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "action" character varying NOT NULL, "targetType" character varying NOT NULL, "targetId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba265816ca1d93f51083e06c520" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_be77588a6727c9a27075b590048" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_65152e15d915ebe1294160bd1d3" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_a436b9dc8304f58060e905eb705" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_d24121b9d08cee2c64630fb7444" FOREIGN KEY ("repoId") REFERENCES "repos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_95770d13d237bc9ca1bf6ad5adb" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repos" ADD CONSTRAINT "FK_10fc186028e0cee03e9a8e5962f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pull_requests" ADD CONSTRAINT "FK_b31de2a04c026344c991d4cb6ba" FOREIGN KEY ("repoId") REFERENCES "repos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pull_requests" ADD CONSTRAINT "FK_b3fb22dd52ef1524e2dcb7ccd33" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" ADD CONSTRAINT "FK_de0f5a4eb77e760a05ec8810ec3" FOREIGN KEY ("pullRequestId") REFERENCES "pull_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" ADD CONSTRAINT "FK_a2419e8f4aa2506efb58010e4a3" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_109de917495c10ad211df0b03e7" FOREIGN KEY ("sprintId") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3" FOREIGN KEY ("assigneeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_7ecc6be7d74a3f441f7aa5215ef" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_12a81f920cc034f4c532766bf18" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_runs" ADD CONSTRAINT "FK_e1ffbb1d3192173b888490c9a28" FOREIGN KEY ("testCaseId") REFERENCES "test_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_runs" ADD CONSTRAINT "FK_bf94964e5f67b91f184c9553568" FOREIGN KEY ("executedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_cases" ADD CONSTRAINT "FK_2448fcc690598b20d52fb7180f6" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deployments" ADD CONSTRAINT "FK_fa2ace72cfb0eb0e2c6e19d56d5" FOREIGN KEY ("environmentId") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deployments" ADD CONSTRAINT "FK_740168ebce85bef4e2e140b55f3" FOREIGN KEY ("deployedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_3e378bf01840fb1c568d64fa87f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "builds" ADD CONSTRAINT "FK_3b3fa0995bf8a730265411ca6ca" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "builds" ADD CONSTRAINT "FK_9d84705cc8b5636edc6e2e3fe62" FOREIGN KEY ("triggeredById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_2f789e58a882d8dd5b936c747c2" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_98d7387cab4021cc58b7c477d1d" FOREIGN KEY ("ownerUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_team_roles" ADD CONSTRAINT "FK_2e9ba57c35c45df17956fb31673" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_team_roles" ADD CONSTRAINT "FK_1d98f4f938837b9b3560835c67b" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_f6ee9774c0683c28751f59d9fd6" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_f6ee9774c0683c28751f59d9fd6"`);
        await queryRunner.query(`ALTER TABLE "user_team_roles" DROP CONSTRAINT "FK_1d98f4f938837b9b3560835c67b"`);
        await queryRunner.query(`ALTER TABLE "user_team_roles" DROP CONSTRAINT "FK_2e9ba57c35c45df17956fb31673"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_98d7387cab4021cc58b7c477d1d"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_2f789e58a882d8dd5b936c747c2"`);
        await queryRunner.query(`ALTER TABLE "builds" DROP CONSTRAINT "FK_9d84705cc8b5636edc6e2e3fe62"`);
        await queryRunner.query(`ALTER TABLE "builds" DROP CONSTRAINT "FK_3b3fa0995bf8a730265411ca6ca"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_3e378bf01840fb1c568d64fa87f"`);
        await queryRunner.query(`ALTER TABLE "deployments" DROP CONSTRAINT "FK_740168ebce85bef4e2e140b55f3"`);
        await queryRunner.query(`ALTER TABLE "deployments" DROP CONSTRAINT "FK_fa2ace72cfb0eb0e2c6e19d56d5"`);
        await queryRunner.query(`ALTER TABLE "test_cases" DROP CONSTRAINT "FK_2448fcc690598b20d52fb7180f6"`);
        await queryRunner.query(`ALTER TABLE "test_runs" DROP CONSTRAINT "FK_bf94964e5f67b91f184c9553568"`);
        await queryRunner.query(`ALTER TABLE "test_runs" DROP CONSTRAINT "FK_e1ffbb1d3192173b888490c9a28"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_12a81f920cc034f4c532766bf18"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_7ecc6be7d74a3f441f7aa5215ef"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_109de917495c10ad211df0b03e7"`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" DROP CONSTRAINT "FK_a2419e8f4aa2506efb58010e4a3"`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" DROP CONSTRAINT "FK_de0f5a4eb77e760a05ec8810ec3"`);
        await queryRunner.query(`ALTER TABLE "pull_requests" DROP CONSTRAINT "FK_b3fb22dd52ef1524e2dcb7ccd33"`);
        await queryRunner.query(`ALTER TABLE "pull_requests" DROP CONSTRAINT "FK_b31de2a04c026344c991d4cb6ba"`);
        await queryRunner.query(`ALTER TABLE "repos" DROP CONSTRAINT "FK_10fc186028e0cee03e9a8e5962f"`);
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_95770d13d237bc9ca1bf6ad5adb"`);
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_d24121b9d08cee2c64630fb7444"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_a436b9dc8304f58060e905eb705"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_65152e15d915ebe1294160bd1d3"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_be77588a6727c9a27075b590048"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba265816ca1d93f51083e06c520"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_platform_role_enum"`);
        await queryRunner.query(`DROP TABLE "user_team_roles"`);
        await queryRunner.query(`DROP TYPE "public"."user_team_roles_role_enum"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP TYPE "public"."teams_type_enum"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "builds"`);
        await queryRunner.query(`DROP TYPE "public"."builds_status_enum"`);
        await queryRunner.query(`DROP TABLE "environments"`);
        await queryRunner.query(`DROP TABLE "deployments"`);
        await queryRunner.query(`DROP TYPE "public"."deployments_status_enum"`);
        await queryRunner.query(`DROP TABLE "test_cases"`);
        await queryRunner.query(`DROP TABLE "test_runs"`);
        await queryRunner.query(`DROP TYPE "public"."test_runs_status_enum"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP TABLE "pr_task_links"`);
        await queryRunner.query(`DROP TABLE "pull_requests"`);
        await queryRunner.query(`DROP TYPE "public"."pull_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "repos"`);
        await queryRunner.query(`DROP TABLE "commits"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TABLE "task_comments"`);
    }

}
