import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSprintsAndTasks1765647966285 implements MigrationInterface {
    name = 'AddSprintsAndTasks1765647966285'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_84759c7bdd530df3fb5bb2ed2bd"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_27c0661e31fbbe5274853141ecc"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_be77588a6727c9a27075b590048"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba265816ca1d93f51083e06c520"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_7ecc6be7d74a3f441f7aa5215ef"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_109de917495c10ad211df0b03e7"`);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("task_id" uuid NOT NULL, "dependency_id" uuid NOT NULL, CONSTRAINT "PK_73f03e2027c01a2cb62d91728d9" PRIMARY KEY ("task_id", "dependency_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ae6688b1bd90fffe857f4cb70" ON "task_dependencies" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6a76113bf7a1956147f19bf75" ON "task_dependencies" ("dependency_id") `);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "archived"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "taskId"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "sprintId"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "assigneeId"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "reporterId"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "goal" text`);
        await queryRunner.query(`CREATE TYPE "public"."sprints_status_enum" AS ENUM('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "status" "public"."sprints_status_enum" NOT NULL DEFAULT 'PLANNED'`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "orderIndex" integer NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "sprints"."orderIndex" IS 'Used for ordering sprints in the UI'`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "task_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "author_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "storyPoints" integer`);
        await queryRunner.query(`COMMENT ON COLUMN "tasks"."storyPoints" IS 'Estimate of effort'`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "orderIndex" integer NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tasks"."orderIndex" IS 'Used for ordering tasks in a list/column'`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "start_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "due_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "sprint_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "assignee_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "reporter_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "parent_task_id" uuid`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_12a81f920cc034f4c532766bf18"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "start_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "end_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "projectId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tasks"."key" IS 'Project-specific key, e.g., PROJ-123'`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'TODO'`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "priority"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM'`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "projectId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_84759c7bdd530df3fb5bb2ed2bd" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_27c0661e31fbbe5274853141ecc" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_12a81f920cc034f4c532766bf18" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba9e465cfc707006e60aae59946" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_76901a920ba9ec5be8dbd64d747" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b512d5a489d692f66569978b8a7" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_c6a76113bf7a1956147f19bf753" FOREIGN KEY ("dependency_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_c6a76113bf7a1956147f19bf753"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b512d5a489d692f66569978b8a7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_76901a920ba9ec5be8dbd64d747"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba9e465cfc707006e60aae59946"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_12a81f920cc034f4c532766bf18"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_27c0661e31fbbe5274853141ecc"`);
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_84759c7bdd530df3fb5bb2ed2bd"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "projectId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "priority"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "priority" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "description" character varying`);
        await queryRunner.query(`COMMENT ON COLUMN "tasks"."key" IS NULL`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "projectId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "end_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_12a81f920cc034f4c532766bf18" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "parent_task_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "reporter_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "assignee_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "sprint_id"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "due_date"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "start_date"`);
        await queryRunner.query(`COMMENT ON COLUMN "tasks"."orderIndex" IS 'Used for ordering tasks in a list/column'`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "orderIndex"`);
        await queryRunner.query(`COMMENT ON COLUMN "tasks"."storyPoints" IS 'Estimate of effort'`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "storyPoints"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "task_id"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "created_at"`);
        await queryRunner.query(`COMMENT ON COLUMN "sprints"."orderIndex" IS 'Used for ordering sprints in the UI'`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "orderIndex"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."sprints_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP COLUMN "goal"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "reporterId" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "assigneeId" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "sprintId" uuid`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "taskId" uuid`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD "archived" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6a76113bf7a1956147f19bf75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ae6688b1bd90fffe857f4cb70"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_109de917495c10ad211df0b03e7" FOREIGN KEY ("sprintId") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3" FOREIGN KEY ("assigneeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_7ecc6be7d74a3f441f7aa5215ef" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba265816ca1d93f51083e06c520" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_be77588a6727c9a27075b590048" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_27c0661e31fbbe5274853141ecc" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_84759c7bdd530df3fb5bb2ed2bd" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
