import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1765893482298 implements MigrationInterface {
    name = 'InitSchema1765893482298'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "commits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hash" character varying NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "repoId" uuid, "authorId" uuid, "taskId" uuid, CONSTRAINT "PK_87adcaf9b8d0f42fee0481c0917" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pr_task_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pullRequestId" uuid, "taskId" uuid, CONSTRAINT "PK_2a5e61688b0e041be6b18719295" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pull_requests_status_enum" AS ENUM('open', 'closed', 'merged')`);
        await queryRunner.query(`CREATE TABLE "pull_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "githubId" bigint NOT NULL, "number" integer NOT NULL, "url" character varying NOT NULL, "title" character varying NOT NULL, "description" text, "status" "public"."pull_requests_status_enum" NOT NULL DEFAULT 'open', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "repoId" uuid, "createdById" uuid, CONSTRAINT "UQ_c3cf03f01a3e60feb84b0be5747" UNIQUE ("githubId"), CONSTRAINT "PK_e8a8aa8710c3a9650a19a9c2e7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "githubUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "taskId" uuid, "repoId" uuid, CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "repos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "githubUrl" character varying NOT NULL, "webhookId" integer, "webhookSecret" character varying, "owner" character varying NOT NULL, "fullName" character varying NOT NULL, "defaultBranch" character varying NOT NULL DEFAULT 'main', "githubId" integer, "isPrivate" boolean NOT NULL DEFAULT true, "patTokenEncrypted" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid, CONSTRAINT "PK_50f4cdbc4e114515f41760400ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."builds_status_enum" AS ENUM('pending', 'success', 'failed', 'running')`);
        await queryRunner.query(`CREATE TABLE "builds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."builds_status_enum" NOT NULL DEFAULT 'pending', "commitHash" character varying NOT NULL, "jenkinsJobName" character varying, "jenkinsBuildNumber" integer, "startedAt" TIMESTAMP NOT NULL DEFAULT now(), "finishedAt" TIMESTAMP, "repoId" uuid, "triggeredById" uuid, CONSTRAINT "PK_c181c897db1d7b044faace6e86c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."deployments_status_enum" AS ENUM('success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "deployments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."deployments_status_enum" NOT NULL, "deployedAt" TIMESTAMP NOT NULL DEFAULT now(), "environmentId" uuid, "deployedById" uuid, "buildId" uuid, CONSTRAINT "REL_1c638197d3d83a6edcf8bbcef7" UNIQUE ("buildId"), CONSTRAINT "PK_1e5627acb3c950deb83fe98fc48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "environments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "projectId" uuid, CONSTRAINT "PK_ec32d12469ec3c2f2f20c4f5e71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid, "userId" uuid, CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pending_project_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, "userId" uuid, CONSTRAINT "PK_efd4a8aee386592512d697e30d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "key_prefix" character varying(4) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sprints_status_enum" AS ENUM('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "goal" text, "status" "public"."sprints_status_enum" NOT NULL DEFAULT 'PLANNED', "orderIndex" integer NOT NULL, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id")); COMMENT ON COLUMN "sprints"."orderIndex" IS 'Used for ordering sprints in the UI'`);
        await queryRunner.query(`CREATE TABLE "task_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "task_id" uuid NOT NULL, "author_id" uuid NOT NULL, CONSTRAINT "PK_83b99b0b03db29d4cafcb579b77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('TODO', 'IN_PROGRESS', 'REVIEW', 'QA', 'BUG', 'DONE', 'BLOCKED')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "title" character varying NOT NULL, "description" text, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'TODO', "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "storyPoints" integer, "orderIndex" integer NOT NULL, "start_date" TIMESTAMP, "due_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "projectId" uuid NOT NULL, "sprint_id" uuid, "assignee_id" uuid, "reporter_id" uuid NOT NULL, "parent_task_id" uuid, CONSTRAINT "UQ_c0abf6686e93b2a6497e0cdc22c" UNIQUE ("key"), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id")); COMMENT ON COLUMN "tasks"."key" IS 'Project-specific key, e.g., PROJ-123'; COMMENT ON COLUMN "tasks"."storyPoints" IS 'Estimate of effort'; COMMENT ON COLUMN "tasks"."orderIndex" IS 'Used for ordering tasks in a list/column'`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "url" character varying NOT NULL, "size" integer, "mimeType" character varying, "public_id" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "taskId" uuid, "uploadedById" uuid, CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying, "name" character varying NOT NULL, "avatar" character varying, "github_token" character varying, "github_name" character varying, "google_id" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "is_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_6f4376a6d5f91d0ed5cf52b72a5" UNIQUE ("github_name"), CONSTRAINT "UQ_0bd5012aeb82628e07f6a1be53b" UNIQUE ("google_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "uploadedById" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "targetType" character varying NOT NULL, "targetId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("task_id" uuid NOT NULL, "dependency_id" uuid NOT NULL, CONSTRAINT "PK_73f03e2027c01a2cb62d91728d9" PRIMARY KEY ("task_id", "dependency_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ae6688b1bd90fffe857f4cb70" ON "task_dependencies" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6a76113bf7a1956147f19bf75" ON "task_dependencies" ("dependency_id") `);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_d24121b9d08cee2c64630fb7444" FOREIGN KEY ("repoId") REFERENCES "repos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_95770d13d237bc9ca1bf6ad5adb" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commits" ADD CONSTRAINT "FK_84759c7bdd530df3fb5bb2ed2bd" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" ADD CONSTRAINT "FK_de0f5a4eb77e760a05ec8810ec3" FOREIGN KEY ("pullRequestId") REFERENCES "pull_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" ADD CONSTRAINT "FK_a2419e8f4aa2506efb58010e4a3" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pull_requests" ADD CONSTRAINT "FK_b31de2a04c026344c991d4cb6ba" FOREIGN KEY ("repoId") REFERENCES "repos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pull_requests" ADD CONSTRAINT "FK_b3fb22dd52ef1524e2dcb7ccd33" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_27c0661e31fbbe5274853141ecc" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_1b78a5ec78a301b17e1ca5af56c" FOREIGN KEY ("repoId") REFERENCES "repos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repos" ADD CONSTRAINT "FK_10fc186028e0cee03e9a8e5962f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "builds" ADD CONSTRAINT "FK_f9430bb22fbd02114ee70ba96fa" FOREIGN KEY ("repoId") REFERENCES "repos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "builds" ADD CONSTRAINT "FK_9d84705cc8b5636edc6e2e3fe62" FOREIGN KEY ("triggeredById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deployments" ADD CONSTRAINT "FK_fa2ace72cfb0eb0e2c6e19d56d5" FOREIGN KEY ("environmentId") REFERENCES "environments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deployments" ADD CONSTRAINT "FK_740168ebce85bef4e2e140b55f3" FOREIGN KEY ("deployedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deployments" ADD CONSTRAINT "FK_1c638197d3d83a6edcf8bbcef78" FOREIGN KEY ("buildId") REFERENCES "builds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "environments" ADD CONSTRAINT "FK_3e378bf01840fb1c568d64fa87f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_d19892d8f03928e5bfc7313780c" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_08d1346ff91abba68e5a637cfdb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pending_project_invitations" ADD CONSTRAINT "FK_83bc3f92b506f2679193e7c7d4c" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pending_project_invitations" ADD CONSTRAINT "FK_79c9ae6887c401e0314f1642306" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_a8e7e6c3f9d9528ed35fe5bae33" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_12a81f920cc034f4c532766bf18" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba9e465cfc707006e60aae59946" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_76901a920ba9ec5be8dbd64d747" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b512d5a489d692f66569978b8a7" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_65152e15d915ebe1294160bd1d3" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_a436b9dc8304f58060e905eb705" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_f6ee9774c0683c28751f59d9fd6" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_c6a76113bf7a1956147f19bf753" FOREIGN KEY ("dependency_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_c6a76113bf7a1956147f19bf753"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_f6ee9774c0683c28751f59d9fd6"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_a436b9dc8304f58060e905eb705"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_65152e15d915ebe1294160bd1d3"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b512d5a489d692f66569978b8a7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_76901a920ba9ec5be8dbd64d747"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba9e465cfc707006e60aae59946"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_12a81f920cc034f4c532766bf18"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_a8e7e6c3f9d9528ed35fe5bae33"`);
        await queryRunner.query(`ALTER TABLE "pending_project_invitations" DROP CONSTRAINT "FK_79c9ae6887c401e0314f1642306"`);
        await queryRunner.query(`ALTER TABLE "pending_project_invitations" DROP CONSTRAINT "FK_83bc3f92b506f2679193e7c7d4c"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_08d1346ff91abba68e5a637cfdb"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_d19892d8f03928e5bfc7313780c"`);
        await queryRunner.query(`ALTER TABLE "environments" DROP CONSTRAINT "FK_3e378bf01840fb1c568d64fa87f"`);
        await queryRunner.query(`ALTER TABLE "deployments" DROP CONSTRAINT "FK_1c638197d3d83a6edcf8bbcef78"`);
        await queryRunner.query(`ALTER TABLE "deployments" DROP CONSTRAINT "FK_740168ebce85bef4e2e140b55f3"`);
        await queryRunner.query(`ALTER TABLE "deployments" DROP CONSTRAINT "FK_fa2ace72cfb0eb0e2c6e19d56d5"`);
        await queryRunner.query(`ALTER TABLE "builds" DROP CONSTRAINT "FK_9d84705cc8b5636edc6e2e3fe62"`);
        await queryRunner.query(`ALTER TABLE "builds" DROP CONSTRAINT "FK_f9430bb22fbd02114ee70ba96fa"`);
        await queryRunner.query(`ALTER TABLE "repos" DROP CONSTRAINT "FK_10fc186028e0cee03e9a8e5962f"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_1b78a5ec78a301b17e1ca5af56c"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_27c0661e31fbbe5274853141ecc"`);
        await queryRunner.query(`ALTER TABLE "pull_requests" DROP CONSTRAINT "FK_b3fb22dd52ef1524e2dcb7ccd33"`);
        await queryRunner.query(`ALTER TABLE "pull_requests" DROP CONSTRAINT "FK_b31de2a04c026344c991d4cb6ba"`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" DROP CONSTRAINT "FK_a2419e8f4aa2506efb58010e4a3"`);
        await queryRunner.query(`ALTER TABLE "pr_task_links" DROP CONSTRAINT "FK_de0f5a4eb77e760a05ec8810ec3"`);
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_84759c7bdd530df3fb5bb2ed2bd"`);
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_95770d13d237bc9ca1bf6ad5adb"`);
        await queryRunner.query(`ALTER TABLE "commits" DROP CONSTRAINT "FK_d24121b9d08cee2c64630fb7444"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6a76113bf7a1956147f19bf75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ae6688b1bd90fffe857f4cb70"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP TABLE "task_comments"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP TYPE "public"."sprints_status_enum"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "pending_project_invitations"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP TABLE "environments"`);
        await queryRunner.query(`DROP TABLE "deployments"`);
        await queryRunner.query(`DROP TYPE "public"."deployments_status_enum"`);
        await queryRunner.query(`DROP TABLE "builds"`);
        await queryRunner.query(`DROP TYPE "public"."builds_status_enum"`);
        await queryRunner.query(`DROP TABLE "repos"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TABLE "pull_requests"`);
        await queryRunner.query(`DROP TYPE "public"."pull_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "pr_task_links"`);
        await queryRunner.query(`DROP TABLE "commits"`);
    }

}
